---
- hosts: all
  remote_user: vagrant
  sudo: yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  vars_files:
    - vars/main.yml
  tasks:
    - include: 'tasks/repository.yml'
    - include: 'tasks/nginx.yml'
    - include: 'tasks/php.yml'
    - include: 'tasks/sys.yml'
    - include: 'tasks/dotfiles.yml'
