---
- hosts: all
  remote_user: vagrant
  sudo: yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  tasks:
    - include: 'tasks/nginx.yml'
    - name: install epel-release
      yum: name=epel-release
    - name: install libraries for shell
      yum: name=zsh
      yum: name=tmux
      yum: name=vim
      yum: name=telnet
      yum: name=redis
